# --- Conjugação manual de 50 verbos irregulares ---
conjugacoes = {
    "be": {"Present": "am / is / are", "Past": "was / were", "Past Participle": "been", "Gerund": "being"},
    "become": {"Present": "become / becomes", "Past": "became", "Past Participle": "become", "Gerund": "becoming"},
    "begin": {"Present": "begin / begins", "Past": "began", "Past Participle": "begun", "Gerund": "beginning"},
    "break": {"Present": "break / breaks", "Past": "broke", "Past Participle": "broken", "Gerund": "breaking"},
    "bring": {"Present": "bring / brings", "Past": "brought", "Past Participle": "brought", "Gerund": "bringing"},
    "build": {"Present": "build / builds", "Past": "built", "Past Participle": "built", "Gerund": "building"},
    "buy": {"Present": "buy / buys", "Past": "bought", "Past Participle": "bought", "Gerund": "buying"},
    "catch": {"Present": "catch / catches", "Past": "caught", "Past Participle": "caught", "Gerund": "catching"},
    "choose": {"Present": "choose / chooses", "Past": "chose", "Past Participle": "chosen", "Gerund": "choosing"},
    "come": {"Present": "come / comes", "Past": "came", "Past Participle": "come", "Gerund": "coming"},
    "cost": {"Present": "cost / costs", "Past": "cost", "Past Participle": "cost", "Gerund": "costing"},
    "cut": {"Present": "cut / cuts", "Past": "cut", "Past Participle": "cut", "Gerund": "cutting"},
    "do": {"Present": "do / does", "Past": "did", "Past Participle": "done", "Gerund": "doing"},
    "draw": {"Present": "draw / draws", "Past": "drew", "Past Participle": "drawn", "Gerund": "drawing"},
    "drink": {"Present": "drink / drinks", "Past": "drank", "Past Participle": "drunk", "Gerund": "drinking"},
    "drive": {"Present": "drive / drives", "Past": "drove", "Past Participle": "driven", "Gerund": "driving"},
    "eat": {"Present": "eat / eats", "Past": "ate", "Past Participle": "eaten", "Gerund": "eating"},
    "fall": {"Present": "fall / falls", "Past": "fell", "Past Participle": "fallen", "Gerund": "falling"},
    "feel": {"Present": "feel / feels", "Past": "felt", "Past Participle": "felt", "Gerund": "feeling"},
    "find": {"Present": "find / finds", "Past": "found", "Past Participle": "found", "Gerund": "finding"},
    "fly": {"Present": "fly / flies", "Past": "flew", "Past Participle": "flown", "Gerund": "flying"},
    "forget": {"Present": "forget / forgets", "Past": "forgot", "Past Participle": "forgotten", "Gerund": "forgetting"},
    "get": {"Present": "get / gets", "Past": "got", "Past Participle": "got / gotten", "Gerund": "getting"},
    "give": {"Present": "give / gives", "Past": "gave", "Past Participle": "given", "Gerund": "giving"},
    "go": {"Present": "go / goes", "Past": "went", "Past Participle": "gone", "Gerund": "going"},
    "grow": {"Present": "grow / grows", "Past": "grew", "Past Participle": "grown", "Gerund": "growing"},
    "have": {"Present": "have / has", "Past": "had", "Past Participle": "had", "Gerund": "having"},
    "hear": {"Present": "hear / hears", "Past": "heard", "Past Participle": "heard", "Gerund": "hearing"},
    "hold": {"Present": "hold / holds", "Past": "held", "Past Participle": "held", "Gerund": "holding"},
    "keep": {"Present": "keep / keeps", "Past": "kept", "Past Participle": "kept", "Gerund": "keeping"},
    "know": {"Present": "know / knows", "Past": "knew", "Past Participle": "known", "Gerund": "knowing"},
    "leave": {"Present": "leave / leaves", "Past": "left", "Past Participle": "left", "Gerund": "leaving"},
    "lose": {"Present": "lose / loses", "Past": "lost", "Past Participle": "lost", "Gerund": "losing"},
    "make": {"Present": "make / makes", "Past": "made", "Past Participle": "made", "Gerund": "making"},
    "meet": {"Present": "meet / meets", "Past": "met", "Past Participle": "met", "Gerund": "meeting"},
    "pay": {"Present": "pay / pays", "Past": "paid", "Past Participle": "paid", "Gerund": "paying"},
    "put": {"Present": "put / puts", "Past": "put", "Past Participle": "put", "Gerund": "putting"},
    "read": {"Present": "read / reads", "Past": "read", "Past Participle": "read", "Gerund": "reading"},
    "run": {"Present": "run / runs", "Past": "ran", "Past Participle": "run", "Gerund": "running"},
    "say": {"Present": "say / says", "Past": "said", "Past Participle": "said", "Gerund": "saying"},
    "see": {"Present": "see / sees", "Past": "saw", "Past Participle": "seen", "Gerund": "seeing"},
    "sell": {"Present": "sell / sells", "Past": "sold", "Past Participle": "sold", "Gerund": "selling"},
    "send": {"Present": "send / sends", "Past": "sent", "Past Participle": "sent", "Gerund": "sending"},
    "sit": {"Present": "sit / sits", "Past": "sat", "Past Participle": "sat", "Gerund": "sitting"},
    "sleep": {"Present": "sleep / sleeps", "Past": "slept", "Past Participle": "slept", "Gerund": "sleeping"},
    "speak": {"Present": "speak / speaks", "Past": "spoke", "Past Participle": "spoken", "Gerund": "speaking"},
    "spend": {"Present": "spend / spends", "Past": "spent", "Past Participle": "spent", "Gerund": "spending"},
    "stand": {"Present": "stand / stands", "Past": "stood", "Past Participle": "stood", "Gerund": "standing"},
    "take": {"Present": "take / takes", "Past": "took", "Past Participle": "taken", "Gerund": "taking"},
    "teach": {"Present": "teach / teaches", "Past": "taught", "Past Participle": "taught", "Gerund": "teaching"},
    "tell": {"Present": "tell / tells", "Past": "told", "Past Participle": "told", "Gerund": "telling"},
    "think": {"Present": "think / thinks", "Past": "thought", "Past Participle": "thought", "Gerund": "thinking"},
    "understand": {"Present": "understand / understands", "Past": "understood", "Past Partic